title: Minischool
email: cermak@mag.mff.cuni.cz
description: "This site is dedicated to czech-bavarian mini-school."
baseurl: ""
url: "https://mini-school.eu/"
future: true
collections:
  - talks
    #output: false
    #permalink: /:collection/:name
defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"