title: Minischool
email: cermak@mag.mff.cuni.cz
description: "This site is dedicated to the regular meetings of the Czech neutron community: neutron beer."
baseurl: ""
url: "https://neutron.beer/"
twitter_username: petrscience
github_username:  me2d09
future: true
collections:
  - talks
    #output: false
    #permalink: /:collection/:name
defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"